WINDOW_NAME = "Focus AI"

ALERT_IMAGE_PATH = "assets/lock_image.jpg"
UNLOCK_PHRASE = "집중하겠습니다"

ABSENT_MODE_THRESHOLD_S = 2.0
TTS_START_THRESHOLD_S = 5.0
FULLSCREEN_IMAGE_THRESHOLD_S = 15.0
FACE_RETURN_REQUIRED_S = 15.0
TTS_REPEAT_INTERVAL_S = 0.5

ROI_WIDTH_RATIO = 0.45
ROI_HEIGHT_RATIO = 0.60

SWAY_WINDOW_S = 3.0
SWAY_THRESHOLD_RATIO = 0.12

FACE_TOUCH_MARGIN = 20

FONT_PATH = r"C:\Windows\Fonts\malgun.ttf"

GOOD_POSTURE_HOLD_S = 3.0
MEAL_PAUSE_LIMIT = 4

MOTIVATION_VIDEO_PATH = "assets/video2.mp4"
VIDEO_FACE_ABSENT_RESTART_S = 30.0
UNLOCK_VIDEO_TRIGGER_COUNT = 5

SESSION_LOG_PATH = "session_log.json"